name: Push to QA

on:
  push:
    branches:
      - dev

jobs:
  push-to-qa:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Push to QA
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git fetch origin qa
          git checkout qa
          git merge dev --no-edit --allow-unrelated-histories
          git push origin qa
