name: Sync Dev to QA

on:
  push:
    branches:
      - dev

jobs:
  sync-dev-to-qa:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Checkout QA branch
        run: git checkout qa

      - name: Merge changes from dev to qa (allow unrelated histories)
        run: git merge origin/dev --allow-unrelated-histories -X theirs --no-edit

      - name: Push changes to QA branch
        run: git push origin qa
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
